version: "2.4"

services:
  aa_setup:
    ports: [ "8545:8545" ]
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile

  alto_bundler:
    image: ghcr.io/pimlicolabs/alto
    ports: [ "3000:3000" ]
    network_mode: "host"
    environment:
      - ALTO_NETWORK_NAME=local
      - ALTO_ENTRY_POINT=0x0000000071727De22E5E9d8BAf0edAc6f37da032 # 0.7
      - ALTO_ENTRY_POINT_SIMULATIONS_ADDRESS=0xe629eB112f891a341Cd2B66b2376ba68e7011241
      - ALTO_ENTRY_POINT_VERSION=0.7
      - ALTO_API_VERSION=v2
      - ALTO_RPC_URL=http://127.0.0.1:8545
      - ALTO_MIN_BALANCE=0
      - ALTO_UTILITY_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 # anvil default key 0
      - ALTO_SIGNER_PRIVATE_KEYS=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d # anvil default key 1
      - ALTO_RPC_MAX_BLOCK_RANGE=10000
      - ALTO_PORT=4337
      - NODE_ENV=development
    depends_on:
      aa_setup:
        condition: service_completed_successfully
